services:
  - type: web
    name: product-listing-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: METAL_PRICE_API_KEY
        sync: false
      - key: GOLDAPI_KEY
        sync: false
      - key: METALS_API_KEY
        sync: false